### ISSUE TITLE
MySQL connection fails

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#58]
I'm setting up RSS Monster on a new machine, and connection to mysql is failing. It looks like the mysql client needs to be updated.
Could you please look into this?
I'm using the dockerhub image which was really simple to setup 😃 

```
   { Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client,
       at Packet.asError (/app/server/node_modules/mysql2/lib/packets/packet.js:684:17),
       at ClientHandshake.execute (/app/server/node_modules/mysql2/lib/commands/command.js:28:26),
       at Connection.handlePacket (/app/server/node_modules/mysql2/lib/connection.js:449:32),
       at PacketParser.Connection.packetParser.p [as onPacket] (/app/server/node_modules/mysql2/lib/connection.js:72:12),
       at Socket.Connection.stream.on.data (/app/server/node_modules/mysql2/lib/connection.js:79:25),
       at PacketParser.executeStart (/app/server/node_modules/mysql2/lib/packet_parser.js:75:16),
       at Socket.emit (events.js:188:13),
       at readableAddChunk (_stream_readable.js:269:11),
       at addChunk (_stream_readable.js:288:12),
       at Socket.Readable.push (_stream_readable.js:224:10),
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17),
     code: 'ER_NOT_SUPPORTED_AUTH_MODE',,
     errno: 1251,,
     sqlState: '08004',,
     sqlMessage:,
      'Client does not support authentication protocol requested by server; consider upgrading MySQL client' } }
```

**Comment by pietheinstrengholt** [comment]
Did you deploy mysql yourself? It should be working, because I have added the following line:

`command: --default-authentication-plugin=mysql_native_password`

**Comment by ThinkChaos** [comment]
Yeah I deployed mysql myself. I added that command line but I still have the same error.
I'll investigate some more later, I haven't compared everything between what I did and what's in the docker-compose.yml yet.

**Comment by ThinkChaos** [comment]
I got it to work by using the same image version as in the docker-compose.yml, I had left it at latest, so it was mysql 8!
